### ISSUE TITLE
Badges without respective logo

### ISSUE THREAD

**Issue by matheus2x** [danmadeira/simple-icon-badges#1]
NEXT.JS and NODE.JS actually without logo:

- <img src="https://img.shields.io/badge/next.js-%23000000.svg?&style=for-the-badge&logo=next.js&logoColor=white" />
`<img src="https://img.shields.io/badge/next.js-%23000000.svg?&style=for-the-badge&logo=next.js&logoColor=white" />`
- <img src="https://img.shields.io/badge/node.js-%23339933.svg?&style=for-the-badge&logo=node.js&logoColor=white" />
 `<img src="https://img.shields.io/badge/node.js-%23339933.svg?&style=for-the-badge&logo=node.js&logoColor=white" />`

**Comment by danmadeira** [comment]
Looking here, both of them are okay. Sometimes it's server instability.
![image](https://user-images.githubusercontent.com/33459555/122035234-a583a500-cda8-11eb-9abf-2724504541d4.png)
![image](https://user-images.githubusercontent.com/33459555/122035306-b92f0b80-cda8-11eb-8c23-ffa31ec5f3f3.png)
